import { internalMutation } from "./_generated/server";

const CATEGORIES = [
  {
    name: "Electronics – Consumer",
    description: "Smartphones, laptops, tablets, TVs, and personal electronics",
    hsCodeRange: "8471, 8517, 8528",
    cetBand: 20,
    dutyRate: 0.2,
    exciseApplicable: false,
    icon: "smartphone",
  },
  {
    name: "Electronics – Industrial",
    description: "Industrial electronic equipment, servers, networking hardware",
    hsCodeRange: "8471, 8537, 8543",
    cetBand: 10,
    dutyRate: 0.1,
    exciseApplicable: false,
    icon: "factory",
  },
  {
    name: "Vehicles – Passenger",
    description: "Cars, SUVs, and personal vehicles",
    hsCodeRange: "8703",
    cetBand: 35,
    dutyRate: 0.35,
    exciseApplicable: false,
    icon: "car",
  },
  {
    name: "Vehicles – Commercial",
    description: "Trucks, buses, and commercial vehicles",
    hsCodeRange: "8704, 8702",
    cetBand: 20,
    dutyRate: 0.2,
    exciseApplicable: false,
    icon: "truck",
  },
  {
    name: "Building Materials",
    description: "Cement, roofing, steel, tiles, and construction materials",
    hsCodeRange: "2523, 7210, 7216, 6905",
    cetBand: 20,
    dutyRate: 0.2,
    exciseApplicable: false,
    icon: "building",
  },
  {
    name: "Food – Basic",
    description: "Rice, sugar, cooking oil, flour, and basic food staples",
    hsCodeRange: "1006, 1701, 1515, 1101",
    cetBand: 5,
    dutyRate: 0.05,
    exciseApplicable: false,
    gstExempt: true,
    icon: "wheat",
  },
  {
    name: "Food – Processed",
    description: "Canned goods, snacks, beverages, and processed food items",
    hsCodeRange: "2009, 1905, 1704, 2106",
    cetBand: 20,
    dutyRate: 0.2,
    exciseApplicable: false,
    icon: "utensils",
  },
  {
    name: "Alcoholic Beverages",
    description: "Beer, wine, spirits, and all alcoholic drinks",
    hsCodeRange: "2203, 2204, 2205, 2208",
    cetBand: 20,
    dutyRate: 0.2,
    exciseApplicable: true,
    exciseRate: 0.3,
    icon: "wine",
  },
  {
    name: "Tobacco Products",
    description: "Cigarettes, cigars, tobacco leaf, and related products",
    hsCodeRange: "2401, 2402, 2403",
    cetBand: 20,
    dutyRate: 0.2,
    exciseApplicable: true,
    exciseRate: 0.35,
    icon: "cigarette",
  },
  {
    name: "Clothing & Textiles",
    description: "Garments, fabrics, shoes, and textile products",
    hsCodeRange: "6101-6117, 6201-6217",
    cetBand: 20,
    dutyRate: 0.2,
    exciseApplicable: false,
    icon: "shirt",
  },
  {
    name: "Machinery & Equipment",
    description: "Industrial machinery, pumps, generators, and equipment",
    hsCodeRange: "8402-8487",
    cetBand: 5,
    dutyRate: 0.05,
    exciseApplicable: false,
    icon: "cog",
  },
  {
    name: "Medical Equipment",
    description: "Diagnostic equipment, surgical instruments, and medical devices",
    hsCodeRange: "9018, 9019, 9022",
    cetBand: 0,
    dutyRate: 0,
    exciseApplicable: false,
    gstExempt: true,
    icon: "heartPulse",
  },
  {
    name: "Pharmaceuticals",
    description: "Medicines, vaccines, medical consumables, and health supplies",
    hsCodeRange: "3001-3006",
    cetBand: 0,
    dutyRate: 0,
    exciseApplicable: false,
    gstExempt: true,
    icon: "pill",
  },
  {
    name: "Furniture",
    description: "Home and office furniture, mattresses, and fixtures",
    hsCodeRange: "9401-9404",
    cetBand: 20,
    dutyRate: 0.2,
    exciseApplicable: false,
    icon: "sofa",
  },
  {
    name: "Agricultural Inputs",
    description: "Seeds, fertilizers, pesticides, and farming equipment",
    hsCodeRange: "3102-3105, 0713, 8432",
    cetBand: 5,
    dutyRate: 0.05,
    exciseApplicable: false,
    gstExempt: true,
    icon: "tractor",
  },
  {
    name: "Petroleum Products",
    description: "Fuel, lubricants, and petroleum-based products",
    hsCodeRange: "2710, 2711",
    cetBand: 10,
    dutyRate: 0.1,
    exciseApplicable: true,
    exciseRate: 0.1,
    icon: "fuel",
  },
  {
    name: "Cosmetics & Toiletries",
    description: "Perfumes, skincare, haircare, and personal care products",
    hsCodeRange: "3301-3307, 3401",
    cetBand: 20,
    dutyRate: 0.2,
    exciseApplicable: false,
    icon: "sparkles",
  },
  {
    name: "Paper & Stationery",
    description: "Paper products, books, notebooks, and printing materials",
    hsCodeRange: "4801-4823, 4901-4911",
    cetBand: 10,
    dutyRate: 0.1,
    exciseApplicable: false,
    icon: "fileText",
  },
  {
    name: "Solar Equipment",
    description: "Solar panels, inverters, batteries, and renewable energy equipment",
    hsCodeRange: "8541.40, 8504",
    cetBand: 0,
    dutyRate: 0,
    exciseApplicable: false,
    gstExempt: true,
    icon: "sun",
  },
  {
    name: "Generators",
    description: "Power generators, UPS systems, and backup power equipment",
    hsCodeRange: "8502",
    cetBand: 10,
    dutyRate: 0.1,
    exciseApplicable: false,
    icon: "zap",
  },
];

export const seedCategories = internalMutation({
  handler: async (ctx) => {
    // Check if categories already exist
    const existing = await ctx.db.query("categories").first();
    if (existing) {
      console.log("Categories already seeded, skipping.");
      return;
    }

    for (const category of CATEGORIES) {
      await ctx.db.insert("categories", category);
    }

    console.log(`Seeded ${CATEGORIES.length} categories.`);
  },
});
